<?php
/**
 * Generated by Vima Mapper. Do not edit manually.
 */

declare(strict_types=1);

namespace App\Mappers\Vima;

use Vima\Core\Support\Mapping\Mappers\EnumMapper;

final class Namespaces extends EnumMapper
{
}
