<?php
/**
 * Generated by Vima Mapper. Do not edit manually.
 */

declare(strict_types=1);

namespace App\Mappers\Vima;

use Vima\Core\Support\Mapping\Mappers\EnumMapper;

final class Permissions extends EnumMapper
{
    public const string EXPENSE_APPROVE = 'expense.approve';
    public const string EXPENSE_CREATE = 'expense.create';
    public const string EXPENSE_READ = 'expense.read';
    public const string PROJECT_CREATE = 'project.create';
    public const string PROJECT_DELETE = 'project.delete';
    public const string PROJECT_READ = 'project.read';
    public const string PROJECT_UPDATE = 'project.update';
}
