<?php
/**
 * Generated by Vima Mapper. Do not edit manually.
 */

declare(strict_types=1);

namespace App\Mappers\Vima;

use Vima\Core\Support\Mapping\Mappers\EnumMapper;

final class Roles extends EnumMapper
{
    public const string ADMIN = 'admin';
    public const string CFO = 'cfo';
    public const string FINANCIER = 'financier';
    public const string MANAGER = 'manager';
    public const string TEAM_LEAD = 'team_lead';
    public const string VIEWER = 'viewer';
}
