/**
 * Generated by Vima Mapper. Do not edit manually.
 */

export const Permissions = {
  EXPENSE_APPROVE: 'expense.approve',
  EXPENSE_CREATE: 'expense.create',
  EXPENSE_READ: 'expense.read',
  PROJECT_CREATE: 'project.create',
  PROJECT_DELETE: 'project.delete',
  PROJECT_READ: 'project.read',
  PROJECT_UPDATE: 'project.update',
} as const;

export type Permissions = typeof Permissions[keyof typeof Permissions];
