/**
 * Generated by Vima Mapper. Do not edit manually.
 */

export const Roles = {
  ADMIN: 'admin',
  CFO: 'cfo',
  FINANCIER: 'financier',
  MANAGER: 'manager',
  TEAM_LEAD: 'team_lead',
  VIEWER: 'viewer',
} as const;

export type Roles = typeof Roles[keyof typeof Roles];
